default_platform(:android)

platform :android do
    desc "Runs all the tests"
    lane :test do
        gradle(task: "test")
    end

    desc "Executes Android lint"
    lane :lint do
        gradle(task: "lintDbcoProdRelease")
    end

    desc "Builds and distributes app via firebase"
    lane :distribute do

        deploy_test

        deploy_acc

        deploy_staging

        deploy_prod


        inform_slack(
            default_payloads: [:git_author],
            message: "Successfully distributed beta builds 1.0.0.#{ENV['GITHUB_RUN_NUMBER']} (#{ENV['GITHUB_RUN_NUMBER']}) :rocket:",
        )
    end

    private_lane :deploy_test do
        build_android_app(
                    task: "assemble",
                    flavor: "dbcoTest",
                    build_type: "Debug"
         )

        firebase_app_distribution(
            app: "1:14711935107:android:ef049bb38e6bad0c074bb6",
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
            groups: "testers",
            release_notes: "Release on test environment via Firebase"
        )
    end


    private_lane :deploy_acc do
            build_android_app(
                        task: "assemble",
                        flavor: "dbcoAcc",
                        build_type: "Release"
             )

            firebase_app_distribution(
                app: "1:514196416954:android:ef32c1bfa34ed40b8f9583",
                firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
                groups: "testers",
                release_notes: "Release on acceptence environment via Firebase"
            )
     end

    private_lane :deploy_staging do
            build_android_app(
                        task: "assemble",
                        flavor: "dbcoStaging",
                        build_type: "Release"
             )

            firebase_app_distribution(
                app: "1:645386815351:android:2076f37379f351626c8372",
                firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
                groups: "testers",
                release_notes: "Release on staging environment via Firebase"
            )
    end

    private_lane :deploy_prod do
             build_android_app(
                         task: "assemble",
                         flavor: "dbcoProd",
                         build_type: "Release"
              )

             firebase_app_distribution(
                 app: "1:1027445500001:android:563963ac88ff228a7ce220",
                 firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
                 groups: "testers",
                 release_notes: "Release on production environment via Firebase"
             )
    end



    private_lane :inform_slack do |options|
        unless ENV['SLACK_URL'].nil?
            slack(options)
        end
    end
end
