default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Executes Android lint"
  lane :lint do
    gradle(task: "lintAccRelease")
  end

  desc "Builds and distributes app via firebase"
  lane :distribute do
      build_android_app(
          task: "assemble",
          flavor: "Acc",
          build_type: "Release"
      )

      firebase_app_distribution(
          app: "1:14711935107:android:5ef53bbc991b05c1074bb6",
          firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
          testers: "testers",
          release_notes: "Trying to release via firebase..."
      )
  end
end
