update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Executes Android lint"
  lane :lint do
    gradle(task: "lintAccRelease")
  end
end
