name: Build and distribute app to Firebase App Distribution

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Get sources
    - name: Checkout
      uses: actions/checkout@v2

    # Setup caches
    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Cache Bundler
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Install ruby and dependencies
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Dependencies
      run: gem install bundler && bundle install

    - name: install firebase tool
      run: |
        yarn global add firebase-tools
        echo "$(yarn global bin)" >> $GITHUB_PATH

    # Generate app bundles...
    - name: Run install fastlane and generate android builds
      run: |
        bundle config set path 'vendor/bundle'
        bundle install
        bundle exec fastlane add_plugin firebase_app_distribution
        bundle exec fastlane android distribute
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
    - uses: actions/upload-artifact@v2
      with:
        name: App-bundle-artifacts
        path: fastlane/distribution
