name: Sigrid CI

on: [pull_request]

jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: "git clone https://github.com/Software-Improvement-Group/sigridci.git sigridci"
      - name: "Run Sigrid CI"
        env:
          SIGRID_CI_ACCOUNT: "${{ secrets.SIGRID_CI_ACCOUNT }}"
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
        run: "./sigridci/sigridci/sigridci.py --customer ggd --system Dbco-app-android --source ./app/src --targetquality 3.0"
      - name: "Save results for Sigrid CI"
        uses: actions/upload-artifact@v2
        with:
          name: sigrid-ci-android
          path: "sigrid-ci-output/**"
          retention-days: 7