name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and test
      run: |
        bundle install
        bundle exec fastlane android test